version: 0.2

phases:

  pre_build:
    commands:
      - echo " hello this is build by manali"
      - echo "Logging in to Docker Hub..."
      - echo "manalijustin" | docker login --username "manalii" --password-stdin
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t manalii/hello-world:latest .
      # - docker tag manalii/roammateapp:latest manalii/roammateapp:$(date +%Y%m%d%H%M%S)
  post_build:
    commands:
      - echo "Pushing the Docker image to Docker Hub..."
      - docker push manalii/hello-world:latest
      # - docker push manalii/roammateapp:$(date +%Y%m%d%H%M%S)
artifacts:
  files:
    - '**/*'
